language: php
php:
  - 7.3
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit test

notifications:
  on_success: never
  on_failure: always