#!/usr/bin/env php
<?php
/**
 * Entrypoint for cli
 */
if($argv[1] == 'new') {
    require_once('new.php');
} else if($argv[1] == 'run') {
    /*$lines = json_decode(file_get_contents('package.json'));
    exec($lines['scripts']['start']);*/
} else if($argv[1] == 'g' || $argv[1] == 'generate') {
    require_once('generate.php');
} else if($argv[1] == 'd' || $argv[1] == 'destroy') {
    require_once('destroy.php');
}